### ISSUE TITLE
EPUB file is no longer built

### ISSUE THREAD

**Issue by leo-liar** [wyattscarpenter/unsong-book-fetcher#20]
Hello there,

I just saw a few new commits in this repo and after pulling these I tried to build an new version of Unsong. Unfortunately only the HTML file got created and no `Unsong.epub`. After a little trying out I realized that – when calling `create_unsong_book.bat` – line 3 isn't executed anymore. For whatever reason the python command in line 2 finishes in such a way that the batch file exits there.

(I'm trying this on Windows 10 in the regular command prompt. Calibre's folders are within my `PATH` variable and manually executing the command from line 3 works and creates the EPUB.)

**Comment by wyattscarpenter** [comment]
Dang, thanks for flagging this!

**Comment by wyattscarpenter** [comment]
I can't reproduce this problem. What kind of command line output do you get? Also, is python known as python or python3 on your system?

I've also pushed a new commit simplifying the bat script in the hopes that this will fix it for you, although I don't see why it would. Hopefully you won't pull this new commit until we can get a little more information about your problem, nail down what it is in particular (or give up on that).

**Comment by leo-liar** [comment]
I only get the regular python output (infos about the fetched images) and the script just terminates.

For testing I tried adding an `echo` and `pause` command but even those won't get executed. ~That's why I'm assuming that the problem is within `get_unsong.py` (maybe related to exit codes).~

Python gets called via `python`.

---

I found the error (it's on my end);
I've apparently made an alias for `python3` to call `python` (forgot when or why I made this) ... When I switch the execution order in `create_unsong_book.bat` to try `python` first then everything works.

**Comment by wyattscarpenter** [comment]
Huh, OK. Thanks for the update!

I guess if your "alias" python3 was a batch script itself, then calling it would mean the original batch script would never resume — a problem I've run into recently myself, in a different project.

So, mystery solved, I guess!

**Comment by leo-liar** [comment]
> I guess if your "alias" python3 was a batch script itself, then calling it would mean the original batch script would never resume — a problem I've run into recently myself, in a different project.

Yes, that's exactly it – which I find astounding ~as I have several other cases with similar aliasing which never lead to this particular problem~.
Right now I just created a `python3.exe` symlink to `python.exe` which also works while I will investigate this further.

Nonetheless this issue can stay closed. Thanks for the feedback!

---

EDIT:
Ah, in my scripts I'm always using the `call` built-in internal command as to prevent [buggy behaviour](https://ss64.com/nt/call.html#:~:text=This%20bug%20can%20be%20avoided%20by%20always%20using%20CALL.). Perhaps `create_unsong_book.bat` could be rewitten to be a true polyglot (with different commands for bash and batch execution). I'll try to put together a PR for that.
